# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EnRouteDialog
                                 A QGIS plugin
 点列に対するルート検索
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-01-18
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Yoichi Kayama/Aeroasahi corporation
        email                : youichi-kayama@aeroasahi.co.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5 import uic
from PyQt5 import QtWidgets
from qgis.core import *
from qgis.gui import *

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'EnRoute_dialog_base.ui'))


class EnRouteDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self,parent=None):
        """Constructor."""
        super(EnRouteDialog, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
#        self.iface = iface
        self.mMapLayerComboBox.setFilters(QgsMapLayerProxyModel.LineLayer)
        self.mMapLayerComboBox_2.setFilters(QgsMapLayerProxyModel.PointLayer)
        self.mMapLayerComboBox_3.setFilters(QgsMapLayerProxyModel.PointLayer)
        
        



